modLoader = "javafml"
loaderVersion = "[0,)"
license = "Powered by Hummel009"
logoFile = "logo.png"

[[mods]]
modId = "dirtequipment"
version = "24.02.29"
displayName = "Dirt Tools and Armor"
authors = "Hummel009"
description = '''This mod adds suppa duppa dirt tools and armor to Minecraft!!!'''

[[dependencies.dirtequipment]]
modId = "neoforge"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dirtequipment]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.1,1.20.4]"
ordering = "NONE"
side = "BOTH"