modLoader = "javafml"
loaderVersion = "[0,)"
license = "GPL-3.0-only"
logoFile = "logo.png"

[[mods]]
modId = "dirtequipment"
version = "24.10.09"
displayName = "Dirt Tools and Armor"
authors = "Hummel009"
description = '''This mod adds a set of tools and armor made from dirt.'''

[[dependencies.dirtequipment]]
modId = "neoforge"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dirtequipment]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"