modLoader = "javafml"
loaderVersion = "[0,)"
license = "GPL-3.0-only"
logoFile = "logo.png"

[[mods]]
modId = "dirtequipment"
version = "24.02.29"
displayName = "Dirt Tools and Armor"
authors = "Hummel009"
description = '''This mod adds a set of tools and armor made from dirt.'''

[[dependencies.dirtequipment]]
modId = "forge"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dirtequipment]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1]"
ordering = "NONE"
side = "BOTH"